using AutoMapper;
using PTFintechTest.DTOs.Request;
using PTFintechTest.Models;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        CreateMap<CreateTaskRequest, PTFintechTest.Models.Task>()
            .ForMember(dest => dest.TaskId, opt => opt.Ignore()) // Ignore mapping TaskId (if auto-generated by DB)
            .ForMember(dest => dest.Labels, opt => opt.Ignore()); // Map Labels collection
        CreateMap<UpdateTaskRequest, PTFintechTest.Models.Task>()
            .ForMember(dest => dest.Labels, opt => opt.Ignore()) // We handle labels manually
            .ForMember(dest => dest.AssignedToNavigation, opt => opt.Ignore());
    }
}