version: '3.4'

services:
  ptfintechtest:
    image: ptfintechtest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=asdasd123;Database=task_management_system
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  # Expose React app on port 3000
    depends_on:
      - ptfintechtest  # Ensure backend is up before starting frontend

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=task_management_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdasd123
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
